In [11]:

import pandas as pd
from sklearn.impute import SimpleImputer # fixiing missing values
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv("all_month.csv")



In [12]:
df.iloc[:,0:2]

time   latitude
0     2025-04-03T03:16:50.230Z  38.840668
1     2025-04-03T03:08:03.540Z  61.556800
2     2025-04-03T02:59:56.724Z  61.789200
3     2025-04-03T02:54:35.248Z  60.081400
4     2025-04-03T02:41:42.280Z  35.639833
...                        ...        ...
9588  2025-03-04T03:25:43.640Z  44.739000
9589  2025-03-04T03:24:58.760Z  37.428500
9590  2025-03-04T03:22:28.320Z  44.726000
9591  2025-03-04T03:20:13.493Z -57.288500
9592  2025-03-04T03:18:45.450Z  39.360500

[9593 rows x 2 columns]

In [13]:
#seperating data into input and output

input_features = df.iloc[:,1:4].values
label = df.iloc[:,5].values

In [15]:
print(input_features)

[[  38.84066772 -122.83433533    1.32000005]
 [  61.5568     -141.2716       13.4       ]
 [  61.7892     -149.6082       38.7       ]
 ...
 [  44.726      -111.12066667    2.38      ]
 [ -57.2885      147.3275       10.        ]
 [  39.3605     -111.1945       -0.61      ]]


In [16]:
#fixing age missing value

lauren_impute = SimpleImputer(missing_values=np.nan,strategy='mean')

In [17]:
lauren_impute.fit(input_features[:,1:4]) #calculating the missing values 
input_features[:, 1:4] = lauren_impute.transform(input_features[:, 1:4]) # making changes

In [20]:
print(input_features)

[[  38.84066772 -122.83433533    1.32000005]
 [  61.5568     -141.2716       13.4       ]
 [  61.7892     -149.6082       38.7       ]
 ...
 [  44.726      -111.12066667    2.38      ]
 [ -57.2885      147.3275       10.        ]
 [  39.3605     -111.1945       -0.61      ]]


In [21]:
# converting two values into 0 and ones
le = LabelEncoder()
label = le.fit_transform(label)
print(label)

[2 4 4 ... 2 0 2]


In [22]:
# data preprocessing using categorical values
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])],remainder='passthrough')

In [23]:
input_features = np.array(ct.fit_transform(input_features))
print(input_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28608 stored elements and shape (9593, 7961)>
  Coords	Values
  (0, 4213)	1.0
  (0, 7959)	-122.83433532715
  (0, 7960)	1.3200000524521
  (1, 7232)	1.0
  (1, 7959)	-141.2716
  (1, 7960)	13.4
  (2, 7325)	1.0
  (2, 7959)	-149.6082
  (2, 7960)	38.7
  (3, 6443)	1.0
  (3, 7959)	-152.5287
  (3, 7960)	97.8
  (4, 2639)	1.0
  (4, 7959)	-117.5485
  (4, 7960)	8.08
  (5, 3920)	1.0
  (5, 7959)	-122.8253326416
  (5, 7960)	1.710000038147
  (6, 7901)	1.0
  (6, 7959)	-148.1959
  (6, 7960)	2.3
  (7, 1924)	1.0
  (7, 7959)	-116.7048333
  (7, 7960)	12.83
  (8, 2512)	1.0
  :	:
  (9584, 7960)	3.45
  (9585, 4827)	1.0
  (9585, 7959)	-111.127
  (9585, 7960)	7.72
  (9586, 6120)	1.0
  (9586, 7959)	-155.37016666667
  (9586, 7960)	1.86
  (9587, 4812)	1.0
  (9587, 7959)	-111.119
  (9587, 7960)	2.72
  (9588, 4822)	1.0
  (9588, 7959)	-111.12333333333
  (9588, 7960)	7.15
  (9589, 3283)	1.0
  (9589, 7959)	-119.0185
  (9589, 7960)	3.69
  (9590, 4811)	1.0
  (959

In [24]:
# finally we have input and label - this one we can train to Machine Learning ALgo
training_input,testing_input,train_label,test_label=train_test_split(input_features,label,test_size=0.1)
# note test_size (0 to 1) ---- here 0.1 means 10% testing data size

TypeError: Input should have at least 1 dimension i.e. satisfy `len(x.shape) > 0`, got scalar `array(<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28608 stored elements and shape (9593, 7961)>, dtype=object)` instead.