In [12]:
!source ./bin/activate

In [34]:
import pandas as pd 
from sklearn.impute import SimpleImputer # fixing missing values 
import numpy as np
from sklearn.preprocessing import LabelEncoder # label encoding for 2 values in single column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [37]:
file = "https://delvex-software-center.s3.ap-south-1.amazonaws.com/USGS/all_month.csv"
df = pd.read_csv(file, usecols=["latitude","longitude","depth","mag"])
print(df.head())

    latitude   longitude  depth   mag
0  38.840668 -122.834335   1.32  0.53
1  61.556800 -141.271600  13.40  1.20
2  61.789200 -149.608200  38.70  1.20
3  60.081400 -152.528700  97.80  1.40
4  35.639833 -117.548500   8.08  0.89


In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   latitude   9593 non-null   float64
 1   longitude  9593 non-null   float64
 2   depth      9593 non-null   float64
 3   mag        9592 non-null   float64
dtypes: float64(4)
memory usage: 299.9 KB


In [39]:
#bottom rows
df.tail()

latitude   longitude  depth   mag
9588   44.7390 -111.123333   7.15 -0.37
9589   37.4285 -119.018500   3.69  1.70
9590   44.7260 -111.120667   2.38 -0.92
9591  -57.2885  147.327500  10.00  4.50
9592   39.3605 -111.194500  -0.61  1.44

In [40]:
df.iloc[:,0:4]

latitude   longitude  depth   mag
0     38.840668 -122.834335   1.32  0.53
1     61.556800 -141.271600  13.40  1.20
2     61.789200 -149.608200  38.70  1.20
3     60.081400 -152.528700  97.80  1.40
4     35.639833 -117.548500   8.08  0.89
...         ...         ...    ...   ...
9588  44.739000 -111.123333   7.15 -0.37
9589  37.428500 -119.018500   3.69  1.70
9590  44.726000 -111.120667   2.38 -0.92
9591 -57.288500  147.327500  10.00  4.50
9592  39.360500 -111.194500  -0.61  1.44

[9593 rows x 4 columns]

In [41]:
#separate into input and output

input_features = df.iloc[:,[0,1,2]].values
label = df.iloc[:,3].values

In [42]:
label

array([ 0.53,  1.2 ,  1.2 , ..., -0.92,  4.5 ,  1.44], shape=(9593,))

In [43]:
input_features

array([[  38.84066772, -122.83433533,    1.32000005],
       [  61.5568    , -141.2716    ,   13.4       ],
       [  61.7892    , -149.6082    ,   38.7       ],
       ...,
       [  44.726     , -111.12066667,    2.38      ],
       [ -57.2885    ,  147.3275    ,   10.        ],
       [  39.3605    , -111.1945    ,   -0.61      ]], shape=(9593, 3))

In [54]:
riley_impute = SimpleImputer(missing_values = np.nan, strategy= 'mean')

In [55]:
riley_impute2 = SimpleImputer(missing_values = np.nan, strategy= 'mean')

In [56]:
riley_impute.fit(input_features[:,0:3])
input_features[:,0:3] = riley_impute.transform(input_features[:,0:3])

In [57]:
riley_impute2.fit(label)
label = riley_impute2.transform(label)

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.53  1.2   1.2  ... -0.92  4.5   1.44].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [46]:
input_features

array([[  38.84066772, -122.83433533,    1.32000005],
       [  61.5568    , -141.2716    ,   13.4       ],
       [  61.7892    , -149.6082    ,   38.7       ],
       ...,
       [  44.726     , -111.12066667,    2.38      ],
       [ -57.2885    ,  147.3275    ,   10.        ],
       [  39.3605    , -111.1945    ,   -0.61      ]], shape=(9593, 3))

In [47]:
#finally we have input and label for training
train_input, test_input, train_label, test_label = train_test_split(input_features, label, test_size = 0.1) 

In [48]:
regression = LinearRegression()

In [49]:
#training classifier with split data
trained_model = regression.fit(train_input,train_label)

ValueError: Input y contains NaN.